#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/harbourmaster-resource-request

cat > $payload <&0

conduit_uri=$(jq -r '.source.conduit_uri // ""' < $payload)
conduit_token=$(jq -r '.source.conduit_token // ""' < $payload)
buildStepPHID=$(jq -r '.source.buildStepPHID // ""' < $payload)

if [ -z "$conduit_uri" ]; then
  echo "invalid payload (missing conduit_uri):" >&2
  cat $payload >&2
  exit 1
fi

if [ -z "$conduit_token" ]; then
  echo "invalid payload (missing conduit_token):" >&2
  cat $payload >&2
  exit 1
fi

if [ -z "$buildStepPHID" ]; then
  echo "invalid payload (missing buildStepPHID):" >&2
  cat $payload >&2
  exit 1
fi

python $(dirname $0)/commands/check.py >&3 < $payload
