#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

bin_dir="${0%/*}"
if [ "${bin_dir#/}" == "$bin_dir" ]; then
  bin_dir="$PWD/$bin_dir"
fi

payload=$(mktemp $TMPDIR/phabricator-pr-resource-request.XXXXXX)

cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

repo_uri=$(jq -r '.source.repo_uri // ""' < $payload)
depth=$(jq -r '(.params.depth // 0)' < $payload)

diff=$(jq -r '.version.diff // 0' < $payload)
version=$(jq -r '.version' < $payload)

configure_git_global "${git_config_payload}"

if [ -z "$repo_uri" ]; then
  echo "invalid payload (missing repo_uri):" >&2
  cat $payload >&2
  exit 1
fi

git clone --single-branch $repo_uri $destination --depth 1
cd $destination

git fetch origin refs/tags/phabricator/diff/$diff:refs/tags/phabricator/diff/$diff
git checkout -b pr phabricator/diff/$diff

jq -n "{version: $(echo $version | jq)}" >&3
